require("dotenv").config();

const TEST_TELEGRAM_CHAT_ID = -1002722070031;

const ALERTS_TELEGRAM_CHAT_ID =
  process.env.IS_TEST === "true" ? TEST_TELEGRAM_CHAT_ID : -1002381170220;

const ABV_TELEGRAM_CHAT_ID =
  process.env.IS_TEST === "true" ? TEST_TELEGRAM_CHAT_ID : -4800060153;

// const ALERTS_TELEGRAM_CHAT_ID = -1002722070031;

const PURCHASE_TELEGRAM_CHAT_ID =
  process.env.IS_TEST === "true" ? TEST_TELEGRAM_CHAT_ID : -4668439381;

const STOCK_CHECKER_TELEGRAM_CHAT_ID =
  process.env.IS_TEST === "true" ? TEST_TELEGRAM_CHAT_ID : -5293267648;

const OFFERS_V3_TELEGRAM_CHAT_ID = process.env.IS_TEST === "true" ? TEST_TELEGRAM_CHAT_ID : -1003706834707;

module.exports = {
  ALERTS_TELEGRAM_CHAT_ID,
  PURCHASE_TELEGRAM_CHAT_ID,
  ABV_TELEGRAM_CHAT_ID,
  TEST_TELEGRAM_CHAT_ID,
  STOCK_CHECKER_TELEGRAM_CHAT_ID,
  OFFERS_V3_TELEGRAM_CHAT_ID,
};
