const logger = require("../utils/logger");

class InvoiceRepository {
  constructor(db) {
    this.db = db;
  }

  // Create invoice with items in a single transaction
  createInvoiceWithItems(invoiceData) {
    return new Promise((resolve, reject) => {
      this.db.getConnection((err, connection) => {
        if (err) {
          logger.Log({
            level: logger.LEVEL.ERROR,
            component: "REPOSITORY.INVOICE",
            code: "REPOSITORY.INVOICE.GET_CONNECTION",
            description: err.toString(),
            category: "",
            ref: {},
          });
          return reject(err);
        }

        connection.beginTransaction(async (err) => {
          if (err) {
            connection.release();
            logger.Log({
              level: logger.LEVEL.ERROR,
              component: "REPOSITORY.INVOICE",
              code: "REPOSITORY.INVOICE.CREATE_TRANSACTION",
              description: err.toString(),
              category: "",
              ref: {},
            });
            return reject(err);
          }

          try {
            // Create invoice
            const invoiceResult = await this.createInvoiceWithConnection(
              connection,
              invoiceData
            );
            if (invoiceResult.code !== 200) {
              throw new Error("Failed to create invoice");
            }

            const invoiceId = invoiceResult.id;

            // Create invoice items
            if (
              invoiceData.invoice_items &&
              invoiceData.invoice_items.length > 0
            ) {
              for (const item of invoiceData.invoice_items) {
                item.invoice_id = invoiceId;
                const itemResult = await this.createInvoiceItemWithConnection(
                  connection,
                  item
                );
                if (itemResult.code !== 200) {
                  throw new Error("Failed to create invoice item");
                }
              }
            }

            // Commit transaction
            connection.commit((err) => {
              if (err) {
                return connection.rollback(() => {
                  connection.release();
                  logger.Log({
                    level: logger.LEVEL.ERROR,
                    component: "REPOSITORY.INVOICE",
                    code: "REPOSITORY.INVOICE.COMMIT",
                    description: err.toString(),
                    category: "",
                    ref: {},
                  });
                  reject(err);
                });
              }
              connection.release();
              resolve({ code: 200, id: invoiceId });
            });
          } catch (error) {
            connection.rollback(() => {
              connection.release();
              logger.Log({
                level: logger.LEVEL.ERROR,
                component: "REPOSITORY.INVOICE",
                code: "REPOSITORY.INVOICE.CREATE_WITH_ITEMS",
                description: error.toString(),
                category: "",
                ref: {},
              });
              reject(error);
            });
          }
        });
      });
    });
  }

  // Create invoice with connection (for transactions)
  createInvoiceWithConnection(connection, invoice) {
    return new Promise((resolve, reject) => {
      const invoiceId = invoice.invoice_id;

      if (invoiceId) {
        // Insert with specific invoice_id
        connection.query(
          `INSERT INTO invoice (invoice_id, created_at, updated_at) VALUES (?, NOW(), NOW())`,
          [invoiceId],
          (err, res) => {
            if (err) {
              if (err.code === "ER_DUP_ENTRY") {
                resolve({ code: 409, msg: "Invoice ID already exists" });
                return;
              }
              logger.Log({
                level: logger.LEVEL.ERROR,
                component: "REPOSITORY.INVOICE",
                code: "REPOSITORY.INVOICE.CREATE",
                description: err.toString(),
                category: "",
                ref: {},
              });
              reject(err);
              return;
            }
            resolve({ code: 200, id: invoiceId });
          }
        );
      } else {
        // Auto-generate invoice_id as string
        const autoGeneratedId =
          "INV-" + Date.now() + "-" + Math.random().toString(36).substr(2, 9);
        connection.query(
          `INSERT INTO invoice (invoice_id, created_at, updated_at) VALUES (?, NOW(), NOW())`,
          [autoGeneratedId],
          (err, res) => {
            if (err) {
              logger.Log({
                level: logger.LEVEL.ERROR,
                component: "REPOSITORY.INVOICE",
                code: "REPOSITORY.INVOICE.CREATE",
                description: err.toString(),
                category: "",
                ref: {},
              });
              reject(err);
              return;
            }
            resolve({ code: 200, id: autoGeneratedId });
          }
        );
      }
    });
  }

  // Create invoice only
  createInvoice(invoice) {
    return new Promise((resolve, reject) => {
      const invoiceId = invoice.invoice_id;

      if (invoiceId) {
        // Insert with specific invoice_id
        this.db.query(
          `INSERT INTO invoice (invoice_id, created_at, updated_at) VALUES (?, NOW(), NOW())`,
          [invoiceId],
          (err, res) => {
            if (err) {
              if (err.code === "ER_DUP_ENTRY") {
                resolve({ code: 409, msg: "Invoice ID already exists" });
                return;
              }
              logger.Log({
                level: logger.LEVEL.ERROR,
                component: "REPOSITORY.INVOICE",
                code: "REPOSITORY.INVOICE.CREATE",
                description: err.toString(),
                category: "",
                ref: {},
              });
              reject(err);
              return;
            }
            resolve({ code: 200, id: invoiceId });
          }
        );
      } else {
        // Auto-generate invoice_id as string
        const autoGeneratedId =
          "INV-" + Date.now() + "-" + Math.random().toString(36).substr(2, 9);
        this.db.query(
          `INSERT INTO invoice (invoice_id, created_at, updated_at) VALUES (?, NOW(), NOW())`,
          [autoGeneratedId],
          (err, res) => {
            if (err) {
              logger.Log({
                level: logger.LEVEL.ERROR,
                component: "REPOSITORY.INVOICE",
                code: "REPOSITORY.INVOICE.CREATE",
                description: err.toString(),
                category: "",
                ref: {},
              });
              reject(err);
              return;
            }
            resolve({ code: 200, id: autoGeneratedId });
          }
        );
      }
    });
  }

  // Create invoice item with connection (for transactions)
  createInvoiceItemWithConnection(connection, invoiceItem) {
    return new Promise((resolve, reject) => {
      connection.query(
        `INSERT INTO invoice_items (invoice_id, product_id, quantity, cost, discount, tax, tax_amount, markup_percentage, final_selling_price, puom, suom, created_at, updated_at) 
         VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, NOW(), NOW())`,
        [
          invoiceItem.invoice_id,
          invoiceItem.product_id,
          invoiceItem.quantity || 0,
          invoiceItem.cost || 0,
          invoiceItem.discount || 0,
          invoiceItem.tax || 0,
          invoiceItem.tax_amount || 0,
          invoiceItem.markup_percentage || 0,
          invoiceItem.final_selling_price || 0,
          invoiceItem.puom || null,
          invoiceItem.suom || null,
        ],
        (err, res) => {
          if (err) {
            logger.Log({
              level: logger.LEVEL.ERROR,
              component: "REPOSITORY.INVOICE",
              code: "REPOSITORY.INVOICE.CREATE_ITEM",
              description: err.toString(),
              category: "",
              ref: {},
            });
            reject(err);
            return;
          }
          resolve({ code: 200, id: res.insertId });
        }
      );
    });
  }

  // Create invoice item
  createInvoiceItem(invoiceItem) {
    return new Promise((resolve, reject) => {
      this.db.query(
        `INSERT INTO invoice_items (invoice_id, product_id, quantity, cost, discount, tax, tax_amount, markup_percentage, final_selling_price, puom, suom, created_at, updated_at) 
         VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, NOW(), NOW())`,
        [
          invoiceItem.invoice_id,
          invoiceItem.product_id,
          invoiceItem.quantity || 0,
          invoiceItem.cost || 0,
          invoiceItem.discount || 0,
          invoiceItem.tax || 0,
          invoiceItem.tax_amount || 0,
          invoiceItem.markup_percentage || 0,
          invoiceItem.final_selling_price || 0,
          invoiceItem.puom || null,
          invoiceItem.suom || null,
        ],
        (err, res) => {
          if (err) {
            logger.Log({
              level: logger.LEVEL.ERROR,
              component: "REPOSITORY.INVOICE",
              code: "REPOSITORY.INVOICE.CREATE_ITEM",
              description: err.toString(),
              category: "",
              ref: {},
            });
            reject(err);
            return;
          }
          resolve({ code: 200, id: res.insertId });
        }
      );
    });
  }

  // Get invoice with items by ID
  getInvoiceWithItems(invoiceId) {
    return new Promise((resolve, reject) => {
      this.db.query(
        `SELECT i.*, 
                ii.invoice_item_id, ii.product_id, ii.quantity, ii.cost, ii.discount, 
                ii.tax, ii.tax_amount, ii.markup_percentage, ii.final_selling_price, 
                ii.puom, ii.suom, ii.created_at as item_created_at, ii.updated_at as item_updated_at
         FROM invoice i
         LEFT JOIN invoice_items ii ON i.invoice_id = ii.invoice_id
         WHERE i.invoice_id = ?`,
        [invoiceId],
        (err, results) => {
          if (err) {
            logger.Log({
              level: logger.LEVEL.ERROR,
              component: "REPOSITORY.INVOICE",
              code: "REPOSITORY.INVOICE.GET_WITH_ITEMS",
              description: err.toString(),
              category: "",
              ref: {},
            });
            reject(err);
            return;
          }

          if (results.length === 0) {
            resolve({ code: 404, msg: "Invoice not found" });
            return;
          }

          // Structure the response
          const invoice = {
            invoice_id: results[0].invoice_id,
            created_at: results[0].created_at,
            updated_at: results[0].updated_at,
            invoice_items: [],
          };

          results.forEach((row) => {
            if (row.invoice_item_id) {
              invoice.invoice_items.push({
                invoice_item_id: row.invoice_item_id,
                product_id: row.product_id,
                quantity: row.quantity,
                cost: row.cost,
                discount: row.discount,
                tax: row.tax,
                tax_amount: row.tax_amount,
                markup_percentage: row.markup_percentage,
                final_selling_price: row.final_selling_price,
                puom: row.puom,
                suom: row.suom,
                created_at: row.item_created_at,
                updated_at: row.item_updated_at,
              });
            }
          });

          resolve({ code: 200, data: invoice });
        }
      );
    });
  }

  // Get all invoices with pagination
  getAllInvoices(limit, offset) {
    return new Promise((resolve, reject) => {
      this.db.query(
        `SELECT * FROM invoice ORDER BY created_at DESC LIMIT ? OFFSET ?`,
        [limit, offset],
        (err, results) => {
          if (err) {
            logger.Log({
              level: logger.LEVEL.ERROR,
              component: "REPOSITORY.INVOICE",
              code: "REPOSITORY.INVOICE.GET_ALL",
              description: err.toString(),
              category: "",
              ref: {},
            });
            reject(err);
            return;
          }
          resolve({ code: 200, data: results });
        }
      );
    });
  }

  // Get invoice count
  getInvoiceCount() {
    return new Promise((resolve, reject) => {
      this.db.query(
        `SELECT COUNT(*) as count FROM invoice`,
        [],
        (err, results) => {
          if (err) {
            logger.Log({
              level: logger.LEVEL.ERROR,
              component: "REPOSITORY.INVOICE",
              code: "REPOSITORY.INVOICE.COUNT",
              description: err.toString(),
              category: "",
              ref: {},
            });
            reject(err);
            return;
          }
          resolve({ code: 200, count: results[0].count });
        }
      );
    });
  }

  // Update invoice with items in a single transaction
  updateInvoiceWithItems(invoiceId, invoiceData) {
    return new Promise((resolve, reject) => {
      this.db.getConnection((err, connection) => {
        if (err) {
          logger.Log({
            level: logger.LEVEL.ERROR,
            component: "REPOSITORY.INVOICE",
            code: "REPOSITORY.INVOICE.GET_CONNECTION",
            description: err.toString(),
            category: "",
            ref: {},
          });
          return reject(err);
        }

        connection.beginTransaction(async (err) => {
          if (err) {
            connection.release();
            logger.Log({
              level: logger.LEVEL.ERROR,
              component: "REPOSITORY.INVOICE",
              code: "REPOSITORY.INVOICE.UPDATE_TRANSACTION",
              description: err.toString(),
              category: "",
              ref: {},
            });
            return reject(err);
          }

          try {
            // Update invoice
            const invoiceResult = await this.updateInvoiceWithConnection(
              connection,
              invoiceId,
              invoiceData
            );
            if (invoiceResult.code !== 200) {
              throw new Error(invoiceResult.msg || "Failed to update invoice");
            }

            // Handle invoice items - implement replace all logic
            if (
              invoiceData.invoice_items &&
              Array.isArray(invoiceData.invoice_items)
            ) {
              // Get all existing items for this invoice
              const existingItems = await this.getAllInvoiceItemsWithConnection(
                connection,
                invoiceId
              );

              // Create a set of product_ids from the new items
              const newProductIds = new Set();
              const newInvoiceItemIds = new Set();

              // Process new items
              for (const item of invoiceData.invoice_items) {
                if (item.invoice_item_id) {
                  // Track items being updated by ID
                  newInvoiceItemIds.add(item.invoice_item_id);
                  
                  // Update existing item by ID
                  const updateResult =
                    await this.updateInvoiceItemWithConnection(
                      connection,
                      item.invoice_item_id,
                      item
                    );
                  if (updateResult.code !== 200) {
                    throw new Error(
                      `Failed to update invoice item: ${item.invoice_item_id}`
                    );
                  }
                } else {
                  // Track product IDs being added/updated
                  newProductIds.add(item.product_id);
                  
                  // Check if product already exists in this invoice
                  const existingItem = await this.getInvoiceItemByProductWithConnection(
                    connection,
                    invoiceId,
                    item.product_id
                  );
                  
                  if (existingItem) {
                    // Update existing item by product_id
                    item.invoice_id = invoiceId;
                    const updateResult =
                      await this.updateInvoiceItemByProductWithConnection(
                        connection,
                        invoiceId,
                        item.product_id,
                        item
                      );
                    if (updateResult.code !== 200) {
                      throw new Error(
                        `Failed to update existing invoice item for product: ${item.product_id}`
                      );
                    }
                  } else {
                    // Create new item
                    item.invoice_id = invoiceId;
                    const createResult =
                      await this.createInvoiceItemWithConnection(
                        connection,
                        item
                      );
                    if (createResult.code !== 200) {
                      throw new Error("Failed to create invoice item");
                    }
                  }
                }
              }

              // Delete items that are not in the new list
              for (const existingItem of existingItems) {
                const shouldDelete = !newInvoiceItemIds.has(existingItem.invoice_item_id) && 
                                   !newProductIds.has(existingItem.product_id);
                
                if (shouldDelete) {
                  const deleteResult = await this.deleteInvoiceItemByProductWithConnection(
                    connection,
                    invoiceId,
                    existingItem.product_id
                  );
                  if (deleteResult.code !== 200) {
                    throw new Error(
                      `Failed to delete invoice item for product: ${existingItem.product_id}`
                    );
                  }
                }
              }
            }

            // Commit transaction
            connection.commit((err) => {
              if (err) {
                return connection.rollback(() => {
                  connection.release();
                  logger.Log({
                    level: logger.LEVEL.ERROR,
                    component: "REPOSITORY.INVOICE",
                    code: "REPOSITORY.INVOICE.COMMIT_UPDATE",
                    description: err.toString(),
                    category: "",
                    ref: {},
                  });
                  reject(err);
                });
              }
              connection.release();
              resolve({
                code: 200,
                msg: "Invoice and items updated successfully",
              });
            });
          } catch (error) {
            connection.rollback(() => {
              connection.release();
              logger.Log({
                level: logger.LEVEL.ERROR,
                component: "REPOSITORY.INVOICE",
                code: "REPOSITORY.INVOICE.UPDATE_WITH_ITEMS",
                description: error.toString(),
                category: "",
                ref: {},
              });
              reject(error);
            });
          }
        });
      });
    });
  }

  // Update invoice with connection (for transactions)
  updateInvoiceWithConnection(connection, invoiceId, invoiceData) {
    return new Promise((resolve, reject) => {
      connection.query(
        `UPDATE invoice SET updated_at = NOW() WHERE invoice_id = ?`,
        [invoiceId],
        (err, results) => {
          if (err) {
            logger.Log({
              level: logger.LEVEL.ERROR,
              component: "REPOSITORY.INVOICE",
              code: "REPOSITORY.INVOICE.UPDATE",
              description: err.toString(),
              category: "",
              ref: {},
            });
            reject(err);
            return;
          }
          if (results.affectedRows === 0) {
            resolve({ code: 404, msg: "Invoice not found" });
            return;
          }
          resolve({ code: 200, msg: "Invoice updated successfully" });
        }
      );
    });
  }

  // Update invoice
  updateInvoice(invoiceId, invoiceData) {
    return new Promise((resolve, reject) => {
      this.db.query(
        `UPDATE invoice SET updated_at = NOW() WHERE invoice_id = ?`,
        [invoiceId],
        (err, results) => {
          if (err) {
            logger.Log({
              level: logger.LEVEL.ERROR,
              component: "REPOSITORY.INVOICE",
              code: "REPOSITORY.INVOICE.UPDATE",
              description: err.toString(),
              category: "",
              ref: {},
            });
            reject(err);
            return;
          }
          if (results.affectedRows === 0) {
            resolve({ code: 404, msg: "Invoice not found" });
            return;
          }
          resolve({ code: 200, msg: "Invoice updated successfully" });
        }
      );
    });
  }

  // Update invoice item with connection (for transactions)
  updateInvoiceItemWithConnection(connection, invoiceItemId, invoiceItemData) {
    return new Promise((resolve, reject) => {
      connection.query(
        `UPDATE invoice_items SET 
         product_id = ?, quantity = ?, cost = ?, discount = ?, tax = ?, 
         tax_amount = ?, markup_percentage = ?, final_selling_price = ?, 
         puom = ?, suom = ?, updated_at = NOW()
         WHERE invoice_item_id = ?`,
        [
          invoiceItemData.product_id,
          invoiceItemData.quantity || 0,
          invoiceItemData.cost || 0,
          invoiceItemData.discount || 0,
          invoiceItemData.tax || 0,
          invoiceItemData.tax_amount || 0,
          invoiceItemData.markup_percentage || 0,
          invoiceItemData.final_selling_price || 0,
          invoiceItemData.puom || null,
          invoiceItemData.suom || null,
          invoiceItemId,
        ],
        (err, results) => {
          if (err) {
            logger.Log({
              level: logger.LEVEL.ERROR,
              component: "REPOSITORY.INVOICE",
              code: "REPOSITORY.INVOICE.UPDATE_ITEM",
              description: err.toString(),
              category: "",
              ref: {},
            });
            reject(err);
            return;
          }
          if (results.affectedRows === 0) {
            resolve({ code: 404, msg: "Invoice item not found" });
            return;
          }
          resolve({ code: 200, msg: "Invoice item updated successfully" });
        }
      );
    });
  }

  // Update invoice item
  updateInvoiceItem(invoiceItemId, invoiceItemData) {
    return new Promise((resolve, reject) => {
      this.db.query(
        `UPDATE invoice_items SET 
         product_id = ?, quantity = ?, cost = ?, discount = ?, tax = ?, 
         tax_amount = ?, markup_percentage = ?, final_selling_price = ?, 
         puom = ?, suom = ?, updated_at = NOW()
         WHERE invoice_item_id = ?`,
        [
          invoiceItemData.product_id,
          invoiceItemData.quantity || 0,
          invoiceItemData.cost || 0,
          invoiceItemData.discount || 0,
          invoiceItemData.tax || 0,
          invoiceItemData.tax_amount || 0,
          invoiceItemData.markup_percentage || 0,
          invoiceItemData.final_selling_price || 0,
          invoiceItemData.puom || null,
          invoiceItemData.suom || null,
          invoiceItemId,
        ],
        (err, results) => {
          if (err) {
            logger.Log({
              level: logger.LEVEL.ERROR,
              component: "REPOSITORY.INVOICE",
              code: "REPOSITORY.INVOICE.UPDATE_ITEM",
              description: err.toString(),
              category: "",
              ref: {},
            });
            reject(err);
            return;
          }
          if (results.affectedRows === 0) {
            resolve({ code: 404, msg: "Invoice item not found" });
            return;
          }
          resolve({ code: 200, msg: "Invoice item updated successfully" });
        }
      );
    });
  }

  // Delete invoice (will cascade delete items)
  deleteInvoice(invoiceId) {
    return new Promise((resolve, reject) => {
      this.db.query(
        `DELETE FROM invoice WHERE invoice_id = ?`,
        [invoiceId],
        (err, results) => {
          if (err) {
            logger.Log({
              level: logger.LEVEL.ERROR,
              component: "REPOSITORY.INVOICE",
              code: "REPOSITORY.INVOICE.DELETE",
              description: err.toString(),
              category: "",
              ref: {},
            });
            reject(err);
            return;
          }
          if (results.affectedRows === 0) {
            resolve({ code: 404, msg: "Invoice not found" });
            return;
          }
          resolve({ code: 200, msg: "Invoice deleted successfully" });
        }
      );
    });
  }

  // Delete invoice item
  deleteInvoiceItem(invoiceItemId) {
    return new Promise((resolve, reject) => {
      this.db.query(
        `DELETE FROM invoice_items WHERE invoice_item_id = ?`,
        [invoiceItemId],
        (err, results) => {
          if (err) {
            logger.Log({
              level: logger.LEVEL.ERROR,
              component: "REPOSITORY.INVOICE",
              code: "REPOSITORY.INVOICE.DELETE_ITEM",
              description: err.toString(),
              category: "",
              ref: {},
            });
            reject(err);
            return;
          }
          if (results.affectedRows === 0) {
            resolve({ code: 404, msg: "Invoice item not found" });
            return;
          }
          resolve({ code: 200, msg: "Invoice item deleted successfully" });
        }
      );
    });
  }

  // Get invoice item by product_id with connection (for transactions)
  getInvoiceItemByProductWithConnection(connection, invoiceId, productId) {
    return new Promise((resolve, reject) => {
      connection.query(
        `SELECT * FROM invoice_items WHERE invoice_id = ? AND product_id = ?`,
        [invoiceId, productId],
        (err, results) => {
          if (err) {
            logger.Log({
              level: logger.LEVEL.ERROR,
              component: "REPOSITORY.INVOICE",
              code: "REPOSITORY.INVOICE.GET_ITEM_BY_PRODUCT",
              description: err.toString(),
              category: "",
              ref: {},
            });
            reject(err);
            return;
          }
          resolve(results.length > 0 ? results[0] : null);
        }
      );
    });
  }

  // Get all invoice items for an invoice with connection (for transactions)
  getAllInvoiceItemsWithConnection(connection, invoiceId) {
    return new Promise((resolve, reject) => {
      connection.query(
        `SELECT * FROM invoice_items WHERE invoice_id = ?`,
        [invoiceId],
        (err, results) => {
          if (err) {
            logger.Log({
              level: logger.LEVEL.ERROR,
              component: "REPOSITORY.INVOICE",
              code: "REPOSITORY.INVOICE.GET_ALL_ITEMS",
              description: err.toString(),
              category: "",
              ref: {},
            });
            reject(err);
            return;
          }
          resolve(results);
        }
      );
    });
  }

  // Delete invoice item by product_id with connection (for transactions)
  deleteInvoiceItemByProductWithConnection(connection, invoiceId, productId) {
    return new Promise((resolve, reject) => {
      connection.query(
        `DELETE FROM invoice_items WHERE invoice_id = ? AND product_id = ?`,
        [invoiceId, productId],
        (err, results) => {
          if (err) {
            logger.Log({
              level: logger.LEVEL.ERROR,
              component: "REPOSITORY.INVOICE",
              code: "REPOSITORY.INVOICE.DELETE_ITEM_BY_PRODUCT",
              description: err.toString(),
              category: "",
              ref: {},
            });
            reject(err);
            return;
          }
          resolve({ code: 200, msg: "Invoice item deleted successfully" });
        }
      );
    });
  }

  // Update invoice item by product_id with connection (for transactions)
  updateInvoiceItemByProductWithConnection(connection, invoiceId, productId, invoiceItemData) {
    return new Promise((resolve, reject) => {
      connection.query(
        `UPDATE invoice_items SET 
         product_id = ?, quantity = ?, cost = ?, discount = ?, tax = ?, 
         tax_amount = ?, markup_percentage = ?, final_selling_price = ?, 
         puom = ?, suom = ?, updated_at = NOW()
         WHERE invoice_id = ? AND product_id = ?`,
        [
          invoiceItemData.product_id,
          invoiceItemData.quantity || 0,
          invoiceItemData.cost || 0,
          invoiceItemData.discount || 0,
          invoiceItemData.tax || 0,
          invoiceItemData.tax_amount || 0,
          invoiceItemData.markup_percentage || 0,
          invoiceItemData.final_selling_price || 0,
          invoiceItemData.puom || null,
          invoiceItemData.suom || null,
          invoiceId,
          productId,
        ],
        (err, results) => {
          if (err) {
            logger.Log({
              level: logger.LEVEL.ERROR,
              component: "REPOSITORY.INVOICE",
              code: "REPOSITORY.INVOICE.UPDATE_ITEM_BY_PRODUCT",
              description: err.toString(),
              category: "",
              ref: {},
            });
            reject(err);
            return;
          }
          if (results.affectedRows === 0) {
            resolve({ code: 404, msg: "Invoice item not found" });
            return;
          }
          resolve({ code: 200, msg: "Invoice item updated successfully" });
        }
      );
    });
  }
}

module.exports = (db) => {
  return new InvoiceRepository(db);
};
