const Joi = require("@hapi/joi");

/** Allows empty string (as sent by Tally) or null; optional on request. */
const emptyStr = () => Joi.string().allow("", null).optional();

const billsAllocationSchema = Joi.object({
  AgstType: emptyStr(),
  Reference: emptyStr(),
  CreditPeriod: Joi.alternatives().try(Joi.number(), Joi.string()).allow(null, ""),
  Amount: Joi.alternatives().try(Joi.number(), Joi.string()).allow(null, ""),
}).unknown(false);

const costCentreAllocationSchema = Joi.object({
  Name: emptyStr(),
  Amount: Joi.alternatives().try(Joi.number(), Joi.string()).allow(null, ""),
}).unknown(false);

const categoryAllocationSchema = Joi.object({
  Category: emptyStr(),
  IsDeemedPositive: emptyStr(),
  isDeeemedPositive: emptyStr(),
  CostCentreAllocation: Joi.array()
    .items(costCentreAllocationSchema)
    .allow(null)
    .optional(),
}).unknown(false);

const ledgerEntrySchema = Joi.object({
  LedgerName: emptyStr(),
  LedgerGroup: emptyStr(),
  GroupName: emptyStr(),
  LedgerAmount: Joi.alternatives().try(Joi.number(), Joi.string()).allow("", null).optional(),
  IsDeemedPositive: emptyStr(),
  IsPartyLedger: emptyStr(),
  GSTClassification: emptyStr(),
  IGSTRate: Joi.alternatives().try(Joi.number(), Joi.string()).allow("", null).optional(),
  HSNCode: emptyStr(),
  Cess_Rate: Joi.alternatives().try(Joi.number(), Joi.string()).allow("", null).optional(),
  BillsAllocation: Joi.alternatives()
    .try(Joi.array().items(billsAllocationSchema), Joi.string().allow(""))
    .optional(),
  CategoryAllocation: Joi.alternatives()
    .try(Joi.array().items(categoryAllocationSchema), Joi.string().allow(""))
    .optional(),
  LedgerDescription: Joi.alternatives()
    .try(Joi.array(), Joi.string().allow(""))
    .optional(),
  BillRefType: emptyStr(),
  AppropriateOnValue: emptyStr(),
}).unknown(false);

/**
 * Full Tally purchase / journal voucher shape (INIT_PURCHASE_ENTRY + INIT_JOURNAL_ENTRY).
 * Empty-string fields are listed explicitly for validation only.
 */
const tallyPurchaseDataSchema = Joi.object({
  MasterID: Joi.string().required(),
  VoucherNumber: Joi.string().required(),
  VoucherDate: Joi.alternatives().try(Joi.string(), Joi.number()).allow("", null).optional(),
  Reference: emptyStr(),
  ReferenceDate: Joi.alternatives().try(Joi.string(), Joi.number()).allow("", null).optional(),
  PartyName: emptyStr(),
  PartyCode: emptyStr(),
  VoucherType: emptyStr(),
  VoucherBaseType: emptyStr(),
  DeliveryNoteNo: emptyStr(),
  Voucher_Total: Joi.alternatives().try(Joi.number(), Joi.string()).allow("", null).optional(),
  DeliveryNoteDate: emptyStr(),
  DispatchDocNo: emptyStr(),
  DispatchThrough: emptyStr(),
  Destination: emptyStr(),
  CarrierName: emptyStr(),
  LRNo: emptyStr(),
  LRDate: emptyStr(),
  MotorVehicleNo: emptyStr(),
  OrderNo: emptyStr(),
  OrderDate: emptyStr(),
  TermsOfPayment: emptyStr(),
  OtherReferences: emptyStr(),
  TermsOfDelivery: emptyStr(),
  PlaceOfSupply: emptyStr(),
  Place_of_Supply: emptyStr(),
  IsInvoice: emptyStr(),
  IsDeleted: emptyStr(),
  BuyerGSTRegistrationType: emptyStr(),
  BuyerName: emptyStr(),
  BuyerAlias: emptyStr(),
  BuyerGSTIN: emptyStr(),
  BuyerAddress: emptyStr(),
  BuyerPinCode: emptyStr(),
  BuyerState: emptyStr(),
  BuyerCountryName: emptyStr(),
  Buyer_Registration_Type: emptyStr(),
  BuyerEmail: emptyStr(),
  BuyerMobile: emptyStr(),
  ConsigneeName: emptyStr(),
  ConsigneeGSTIN: emptyStr(),
  ConsigneeAddress: emptyStr(),
  ConsigneePinCode: emptyStr(),
  ConsigneeState: emptyStr(),
  ConsigneeCountryName: emptyStr(),
  ConsigneeTallyGroup: emptyStr(),
  Consignee_Registration_Type: emptyStr(),
  VoucherCostCentre: emptyStr(),
  Narration: emptyStr(),
  EWayBillDetails: emptyStr(),
  EInvoiceDetails: emptyStr(),
  item_total: Joi.alternatives().try(Joi.number(), Joi.string()).allow("", null).optional(),
  SVViewName: emptyStr(),
  GSTREGISTRATIONTYPE: emptyStr(),
  PurOrder: emptyStr(),
  PurOrderID: emptyStr(),
  WorkOrder: emptyStr(),
  WorkOrderID: emptyStr(),
  ledgerentries: Joi.array().items(ledgerEntrySchema).default([]),
}).unknown(false);

const gstTallyPurchaseRequestSchema = Joi.object({
  action: Joi.string().valid("create", "update", "delete").required(),
  data: tallyPurchaseDataSchema.required(),
});

/** Default empty purchase voucher payload (validation reference). */
const TALLY_PURCHASE_DATA_TEMPLATE = {
  MasterID: "",
  VoucherNumber: "",
  VoucherDate: "",
  Reference: "",
  ReferenceDate: "",
  PartyName: "",
  PartyCode: "",
  VoucherType: "",
  DeliveryNoteNo: "",
  Voucher_Total: "",
  DeliveryNoteDate: "",
  DispatchThrough: "",
  Destination: "",
  CarrierName: "",
  LRNo: "",
  LRDate: "",
  MotorVehicleNo: "",
  OrderNo: "",
  OrderDate: "",
  TermsOfPayment: "",
  OtherReferences: "",
  TermsOfDelivery: "",
  PlaceOfSupply: "Puducherry",
  IsInvoice: "Yes",
  IsDeleted: "",
  BuyerGSTRegistrationType: "",
  BuyerName: "",
  BuyerAlias: "",
  BuyerGSTIN: "",
  BuyerAddress: "",
  BuyerPinCode: "",
  BuyerState: " ",
  BuyerCountryName: "India",
  BuyerEmail: "",
  BuyerMobile: "",
  ConsigneeName: "Dailyneeds Department Store",
  ConsigneeGSTIN: "34AAJFD4987C1ZD",
  ConsigneeAddress: ",",
  ConsigneePinCode: "",
  ConsigneeState: "Puducherry",
  ConsigneeCountryName: "India",
  VoucherCostCentre: "",
  Narration: "",
  EWayBillDetails: "",
  EInvoiceDetails: "",
  item_total: "",
  SVViewName: "InvVchView",
  ledgerentries: [],
};

/** Default empty journal voucher payload (validation reference). */
const TALLY_JOURNAL_DATA_TEMPLATE = {
  MasterID: "",
  VoucherNumber: "",
  VoucherDate: "",
  Reference: "",
  ReferenceDate: "",
  PartyName: "",
  VoucherType: "Journal",
  DeliveryNoteNo: "",
  Voucher_Total: "",
  DeliveryNoteDate: "",
  DispatchDocNo: "",
  DispatchThrough: "",
  Destination: "",
  CarrierName: "",
  LRNo: "",
  LRDate: "",
  MotorVehicleNo: "",
  OrderNo: "",
  OrderDate: "",
  TermsOfPayment: "",
  OtherReferences: "",
  TermsOfDelivery: "",
  Place_of_Supply: "",
  IsInvoice: "No",
  BuyerGSTRegistrationType: "",
  BuyerName: "",
  BuyerAlias: "",
  BuyerGSTIN: "",
  BuyerAddress: "",
  BuyerPinCode: "",
  BuyerState: "",
  BuyerCountryName: "",
  Buyer_Registration_Type: "",
  BuyerEmail: "",
  BuyerMobile: "",
  ConsigneeName: "",
  ConsigneeAddress: "",
  ConsigneeGSTIN: "",
  ConsigneeTallyGroup: "",
  ConsigneePinCode: "",
  ConsigneeState: "",
  ConsigneeCountryName: "",
  VoucherCostCentre: "",
  Consignee_Registration_Type: "Unregistered/Consumer",
  Narration: "",
  PurOrder: "",
  PurOrderID: "",
  WorkOrder: "",
  WorkOrderID: "",
  SVViewName: "AccVchView",
  ledgerentries: [],
};

module.exports = {
  tallyPurchaseDataSchema,
  gstTallyPurchaseRequestSchema,
  TALLY_PURCHASE_DATA_TEMPLATE,
  TALLY_JOURNAL_DATA_TEMPLATE,
};
