CREATE TABLE `debit_note` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `store_id` int(11) NOT NULL,
  `mprh_pr_no` varchar(20) NOT NULL,
  `mprh_pr_refno` varchar(20) NOT NULL,
  `mprh_pr_dt` date NOT NULL,
  `mprh_dist_code` varchar(20) NOT NULL,
  `supplier_id` varchar(20) NOT NULL,
  `supplier_name` varchar(100) NOT NULL,
  `supplier_gstn` varchar(20) NOT NULL,
  `tot_sgst_amt` decimal(10,2) NOT NULL DEFAULT 0.00,
  `tot_cgst_amt` decimal(10,2) NOT NULL DEFAULT 0.00,
  `tot_igst_amt` decimal(10,2) NOT NULL DEFAULT 0.00,
  `tot_gst_cess_amt` decimal(10,2) NOT NULL DEFAULT 0.00,
  `tot_item_qty` decimal(10,2) NOT NULL DEFAULT 0.00,
  `tot_item_value` decimal(10,2) NOT NULL DEFAULT 0.00,
  `ts` bigint(20) NOT NULL,
  `sgst` json NOT NULL,
  `cgst` json NOT NULL,
  `igst` json NOT NULL,
  `cess` json NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `mprh_pr_refno` (`mprh_pr_refno`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;