CREATE TABLE `product_distributor_master` (
  `mdm_dist_code` INT NOT NULL,
  `mdm_dist_name` VARCHAR(255) NULL DEFAULT NULL,
  `mdm_short_name` VARCHAR(255) NULL DEFAULT NULL,
  `cid` VARCHAR(64) NULL DEFAULT NULL,
  `mdm_tag` VARCHAR(16) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`mdm_dist_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
