CREATE TABLE `offer_hdr` (
  `moh_offer_id` BIGINT NOT NULL,
  `moh_offer_name` VARCHAR(150) NULL DEFAULT NULL,
  `moh_offer_family_id` BIGINT NULL DEFAULT NULL,
  `moh_offer_typeid` BIGINT NULL DEFAULT NULL,
  `moh_offer_status` BIGINT NULL DEFAULT NULL,
  `moh_offer_get_confirm` BIGINT NULL DEFAULT NULL,
  `moh_offer_tier_id` BIGINT NULL DEFAULT NULL,
  `moh_offer_period` BIGINT NULL DEFAULT NULL,
  `moh_offer_happy_days` BIGINT NULL DEFAULT NULL,
  `moh_offer_happy_hours` BIGINT NULL DEFAULT NULL,
  `moh_offer_first_n_customers` BIGINT NULL DEFAULT NULL,
  `moh_offer_st_date` DATE NULL DEFAULT NULL,
  `moh_offer_end_date` DATE NULL DEFAULT NULL,
  `moh_offer_hq_id` BIGINT NULL DEFAULT NULL,
  `moh_offer_nth_bill` BIGINT NULL DEFAULT NULL,
  `ts` DATE NULL DEFAULT NULL,
  `tsid` BIGINT NULL DEFAULT NULL,
  `retail_outlet_id` INT(11) NOT NULL,
  `moh_vertical_id` BIGINT NULL DEFAULT NULL,
  `moh_offer_cust_type` BIGINT NULL DEFAULT NULL,
  `timestamp` VARCHAR(30) NULL DEFAULT NULL,
  `moh_allow_span` BIGINT NULL DEFAULT NULL,
  `moh_offer_on_nextbill` BIGINT NULL DEFAULT NULL,
  `moh_loyalty_card_must` BIGINT NULL DEFAULT NULL,
  `hq_timestamp_id` BIGINT NOT NULL DEFAULT 0,
  `moh_offer_on_eachitem` BIGINT NULL DEFAULT NULL,
  `moh_first_time_offer` BIGINT NULL DEFAULT NULL,
  `moh_offer_basedon_mrp` BIGINT NULL DEFAULT NULL,
  `moh_happy_hours_basedon` BIGINT NULL DEFAULT NULL,
  `moh_offer_on_itemuom` BIGINT NULL DEFAULT NULL,
  `moh_batch_offer` BIGINT NULL DEFAULT NULL,
  `moh_override_duplicate` BIGINT NULL DEFAULT NULL,
  `moh_block_return` BIGINT NULL DEFAULT NULL,
  `moh_cust_specific_offer` BIGINT NULL DEFAULT NULL,
  `moh_loyalty_point` DECIMAL(20, 4) NULL DEFAULT NULL,
  `moh_offer_st_day` BIGINT NULL DEFAULT NULL,
  `moh_offer_end_day` BIGINT NULL DEFAULT NULL,
  `moh_offer_sales_period` BIGINT NULL DEFAULT NULL,
  `moh_offer_sales_st_dt` DATE NULL DEFAULT NULL,
  `moh_offer_sales_end_dt` DATE NULL DEFAULT NULL,
  `moh_allow_max_qty` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`moh_offer_id`, `retail_outlet_id`),
  CONSTRAINT `fk_offer_hdr_outlet` FOREIGN KEY (`retail_outlet_id`) REFERENCES `outlets` (`outlet_id`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
